opt_in_rules:
- closure_end_indentation
- closure_spacing
- empty_count
- explicit_init
- fatal_error_message
- file_header
- first_where
- implicitly_unwrapped_optional
- no_extension_access_modifier
- number_separator
- operator_usage_whitespace
- redundant_nil_coalescing
- unneeded_parentheses_in_closure_argument

disabled_rules:
- closure_end_indentation
- function_parameter_count
- identifier_name
- no_fallthrough_only # https://github.com/realm/SwiftLint/issues/2276
- redundant_string_enum_value
- superfluous_disable_comman
- unused_closure_parameter

excluded:
- Carthage

line_length:
  ignores_comments: true
  ignores_function_declarations: true

file_length:
  ignore_comment_only_lines: true
